# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_yar_wrappers", use_symbols = TRUE, package_name = "yar")

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

ArDoc <- new.env(parent = emptyenv())

ArDoc$new <- function() .Call(wrap__ArDoc__new)

ArDoc$client_id <- function() .Call(wrap__ArDoc__client_id, self)

#' @export
`$.ArDoc` <- function (self, name) { func <- ArDoc[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ArDoc` <- `$.ArDoc`

# nolint end
